create table if not exists posts(
    id bigint not null AUTO_INCREMENT PRIMARY KEY,
    user_id bigint not null,
    title varchar(255) not null default "",
    slug varchar(255) not null unique default "",
    description varchar(255) not null default "",
    content text not null,
    delta text not null default "",
    created_at datetime not null default CURRENT_TIMESTAMP,
    updated_at datetime not null default CURRENT_TIMESTAMP,
    status enum("draft", "published", "scheduled") default "draft",
    version int not null default 1,
    foreign key (user_id) references users(id) on delete cascade
);

create index slug_idx ON posts (slug);

INSERT INTO posts (
    id,
    user_id,
    title,
    slug,
    description,
    content,
    created_at,
    updated_at,
    status,
    version
) VALUES
(
    1,
    1,
    "Test Post Happiness",
    "/2024/10/19/test-post-happiness",
    "This is a test post",
    "<h1>Heading 1 Text</h1><h2>Heading 2 Text</h2><h3>Heading 3 Text</h3><h4>Heading 4 Text</h4><h5>Heading 5 Text</h5><h6>Heading 6 Text</h6><p></p><p><strong>Lorem ipsum </strong>odor amet, <em>consectetuer adipiscing elit.</em> <u>Pulvinar posuere eget potenti pellentesque maecenas per</u>. <s>Varius vivamus lobortis massa adipiscing;</s> ut non nostra. Dictum inceptos nibh placerat elit tempus mi pharetra. Eleifend parturient per scelerisque id posuere donec praesent vivamus parturient. Adipiscing tortor aenean est nostra vehicula platea sagittis donec mollis. Facilisi tempus scelerisque etiam egestas eleifend etiam id eget maecenas. Ultricies nunc suspendisse ex platea imperdiet commodo commodo ad. Eleifend rutrum in aptent semper adipiscing, lorem eleifend.</p><p></p><blockquote>Lorem ipsum odor amet, consectetuer adipiscing elit. Pulvinar posuere eget potenti pellentesque maecenas per. Varius vivamus lobortis massa adipiscing; ut non nostra. Dictum inceptos nibh placerat elit tempus mi pharetra. Eleifend parturient per scelerisque id posuere donec praesent vivamus parturient. Adipiscing tortor aenean est nostra vehicula platea sagittis donec mollis. Facilisi tempus scelerisque etiam egestas eleifend etiam id eget maecenas. Ultricies nunc suspendisse ex platea imperdiet commodo commodo ad. Eleifend rutrum in aptent semper adipiscing, lorem eleifend.</blockquote><p></p><p><img src=\"/uploads/2/arctic-landscape.png\"></p><pre data-language=\"plain\">\nalert(\"hello world\");\n</pre><p><a href=\"https://www.andrew-mccall.com\" rel=\"noopener noreferrer\" target=\"_blank\">I am a link</a></p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    2,
    1,
    "Sample Post Delight",
    "/2024/10/20/sample-post-delight",
    "This is a sample post",
    "<p>Content for sample post delight. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    3,
    1,
    "Another Day, Another Post",
    "/2024/10/21/another-day-another-post",
    "Daily reflection on coding",
    "<p>Reflections on coding and development on this day.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    4,
    1,
    "Tech Talk and Trends",
    "/2024/10/22/tech-talk-and-trends",
    "Exploring technology trends",
    "<p>Discussion on the latest technology trends and insights.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    5,
    1,
    "Daily Developer Diary",
    "/2024/10/23/daily-developer-diary",
    "A day in the life of a developer",
    "<p>An insightful journey through a day in the life of a developer.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    6,
    1,
    "Career Pathways in Tech",
    "/2024/10/24/career-pathways-in-tech",
    "Exploring career opportunities",
    "<p>An exploration of various career pathways in the tech industry.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    7,
    1,
    "Developer Motivation Tips",
    "/2024/10/25/developer-motivation-tips",
    "Tips for staying motivated",
    "<p>Effective tips for maintaining motivation as a developer.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    8,
    1,
    "Innovative Coding Practices",
    "/2024/10/26/innovative-coding-practices",
    "Staying ahead with innovative practices",
    "<p>Innovative coding practices that keep developers ahead.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    9,
    1,
    "Understanding Cloud Computing",
    "/2024/10/27/understanding-cloud-computing",
    "Basics of cloud computing",
    "<p>An introduction to the fundamentals of cloud computing.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    10,
    1,
    "Managing Remote Teams",
    "/2024/10/28/managing-remote-teams",
    "Best practices for remote team management",
    "<p>Insightful best practices for effective management of remote teams.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    11,
    1,
    "Agile Practices in Development",
    "/2024/10/29/agile-practices-in-development",
    "Understanding Agile methodologies",
    "<p>An in-depth look at Agile methodologies in software development.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    12,
    1,
    "Guide to RESTful APIs",
    "/2024/10/30/guide-to-restful-apis",
    "Building and using RESTful APIs",
    "<p>A comprehensive guide to building and consuming RESTful APIs.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    13,
    1,
    "Securing Web Applications",
    "/2024/10/31/securing-web-applications",
    "Essential security practices",
    "<p>Essential practices for securing web applications from threats.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    14,
    1,
    "Performance Optimization Tips",
    "/2024/11/01/performance-optimization-tips",
    "Boosting application performance",
    "<p>Proven tips to boost the performance of software applications.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    15,
    1,
    "Design Patterns in Coding",
    "/2024/11/02/design-patterns-in-coding",
    "Understanding design patterns",
    "<p>An introduction to common design patterns in software engineering.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    16,
    1,
    "DevOps for Developers",
    "/2024/11/03/devops-for-developers",
    "Integrating DevOps practices",
    "<p>How developers can integrate DevOps practices in their workflows.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    17,
    1,
    "Data Structures and Algorithms",
    "/2024/11/04/data-structures-and-algorithms",
    "The foundations of algorithms",
    "<p>A closer look at essential data structures and algorithms.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    18,
    1,
    "Introduction to Machine Learning",
    "/2024/11/05/introduction-to-machine-learning",
    "Basics of machine learning",
    "<p>An introduction to the basics of machine learning and its applications.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    19,
    1,
    "Blockchain and Cryptocurrency",
    "/2024/11/06/blockchain-and-cryptocurrency",
    "Understanding blockchain",
    "<p>An overview of blockchain technology and its link to cryptocurrency.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    20,
    1,
    "Exploring Artificial Intelligence",
    "/2024/11/07/exploring-artificial-intelligence",
    "AI in modern tech",
    "<p>Exploring the impact and potential of artificial intelligence.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    21,
    1,
    "The Future of Quantum Computing",
    "/2024/11/08/the-future-of-quantum-computing",
    "Possibilities with quantum computing",
    "<p>A look into the future potential of quantum computing.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    22,
    1,
    "Understanding Microservices",
    "/2024/11/09/understanding-microservices",
    "The microservices architecture",
    "<p>An exploration of microservices architecture and its benefits.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    23,
    1,
    "The Rise of Serverless Computing",
    "/2024/11/10/the-rise-of-serverless-computing",
    "Exploring serverless architectures",
    "<p>Examining the rise and advantages of serverless computing.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    24,
    1,
    "Navigating the World of IoT",
    "/2024/11/11/navigating-the-world-of-iot",
    "Understanding the Internet of Things",
    "<p>Understanding how IoT is reshaping various industries.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
),
(
    25,
    1,
    "Enhancing UI/UX in Your Apps",
    "/2024/11/12/enhancing-ui-ux-in-your-apps",
    "Improving user interfaces and experiences",
    "<p>Strategies for improving UI/UX design in software applications.</p>",
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    "published",
    1
);


